docker-compose.yml

현재 작업중인 개발 컴퓨터에서 postgres 데이터베이스를 컨테이너로 가져와 실행시키는
docker-compose.yml 파일입니다. 
docker-compose.yml 파일이있는 위치 ( 8term-coko-back/docker-compose.yml ) 에서 
`docker-compose up` 명령어를 치면 postgres 컨테이너가 실행됩니다.
8term-coko-back / postgres-data 디렉토리에 컨테이너의 데이터가 저장되서 컨테이너가 꺼져도 자료가 남아있습니다.
`docker-compose up` 실행시 자동으로 8term-coko-back / postgres-data 디렉토리가 생성되지만
혹시 8term-coko-back / postgres-data 가 없다면 만들어 주시면 됩니다. 
postgres 접근은 `localhost:5432` 입니다.
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: postgres
도 참고하시면 되겠습니다. 컴포즈 안에 내용이 있습니다.

로컬에서 간단하게 쓸 postgres 데이터베이스

---

prisma/migrations/20241021064303_/migration.sql
prisma/schema.prisma
src/main.ts
src/users/controllers/user-experience.controller.ts
src/users/controllers/user-point.controller.ts
src/users/controllers/users.controller.ts
src/users/dtos/create-user.dto.ts
src/users/dtos/response-experience.dto.ts
src/users/dtos/response-point.dto.ts
src/users/dtos/response-user.dto.ts
src/users/dtos/update-experience.dto.ts
src/users/dtos/update-point.dto.ts
src/users/dtos/update-user.dto.ts
src/users/services/user-experience.service.ts
src/users/services/user-point.service.ts
src/users/services/users.service.ts
src/users/swagger-dacorator/delete-user-decorators.ts
src/users/swagger-dacorator/get-all-users-decorators.ts
src/users/swagger-dacorator/get-user-decorators.ts
src/users/swagger-dacorator/get-user-experience-decorators.ts
src/users/swagger-dacorator/get-user-point-decorators.ts
src/users/swagger-dacorator/patch-user-decorators.ts
src/users/swagger-dacorator/patch-user-experience-decorators.ts
src/users/swagger-dacorator/patch-user-point-decorators.ts
src/users/swagger-dacorator/post-user-decorators.ts

#16 
- **Swagger 의존성 설치** 후 main.ts 파일에 전체적인 Swagger document 세팅
→ Swagger로 사용할 **URI, 태그들, 버전, 라이센스** 등 을 설정함
- 각 요청 DTO에 **@ApiProperty**를 작성
→ Swagger 페이지에서 **Schemas 의 DTO 정보**를 알려줌
- 컨트롤러에서 각 요청 정보 세팅했는데 컨트롤러 코드가 너무 길어지기 때문에 
**Swagger 데코레이터 파일로 분리** 시켰음
→ 이는 **각 요청의 정보**를 알려줌 ( 어떤 요청인지, 상황별 요청의 응답이 어떻게 되는지,
content에 **상태코드, 응답 데이터**들이 담겨있음) 
- Swagger 문서를 작성했습니다
-  `http://localhost:3000/api` 에서 Swagger 문서를 확인할 수 있습니다 
```
// main.ts
SwaggerModule.setup('api', app, document);
```
경로 설정 부분입니다

User Swagger 문서 생성

---

src/progress/progress.service.ts

#26 
이전 `GET users/progress` 요청은
```JSON
[
{
"userId": 1,
"quizId": 5,
"isCorrect": true,
"createdAt": "2024-11-08T05:20:38.468Z",
"updatedAt": "2024-11-08T05:20:38.468Z"
},
{
"userId": 1,
"quizId": 6,
"isCorrect": true,
"createdAt": "2024-11-08T05:20:44.285Z",
"updatedAt": "2024-11-08T05:20:44.285Z"
},
{
"userId": 1,
"quizId": 7,
"isCorrect": false,
"createdAt": "2024-11-08T05:20:56.004Z",
"updatedAt": "2024-11-08T05:20:56.004Z"
}
]
```
형식의 `response` 를 보내줬습니다. 유저가 푼 문제와 세부 내용을 모두 보내줬습니다.
이 형식을 
```JSON
{
"totalQuizCount": 2,                       // 전체 문제 수
"totalUserProgressCount": 1,        // 유저가 푼 문제 수
"correctUserProgressCount": 0,   // 유저가 맞힌 문제 수
"inCorrectUserProgressCount": 1 // 유저가 틀린 문제 수
}
```
형식으로 변경합니다.
`전체 문제`와 `유저가 푼 문제`를 구별하는건  유저가 한번도 풀지 않은 문제가 통계에 들어가지 않는걸 막기 위해서 입니다. …

진행도 response 변경

---

src/quizzes/quizzes.controller.ts
src/quizzes/quizzes.service.ts
src/quizzes/quizzes.swagger.ts

#33 
1. `GET /quizzes/users/{id}/incorrect` api 엔드포인트가 하나 생성됬습니다.
이제 이 요청을 통해서 유저가 풀었던 문제들 중 정답을 틀렸던 문제들 배열로 받을 수 있습니다.
2. 관련 api에 대한 스웨거 문서 설정이 되었습니다.
(수정사항)
3. 유저의 모든 문제 중 틀린문제만 받게 설정되었던걸 -> query를 사용해 part와 section별로 받을 수 있도록 수정했습니다.

새로운 quizze api , 정답을 틀렸던 문제들을 받기

---

prisma/migrations/20241209140233_part_progress_create/migration.sql
prisma/schema.prisma
src/app.module.ts
src/common/util/type-utils.ts
src/part-progress/dto/create-part-progress.dto.ts
src/part-progress/dto/res-part-progress.dto.ts
src/part-progress/dto/update-part-progress.dto.ts
src/part-progress/entities/part-progress.entity.ts
src/part-progress/part-progress.controller.spec.ts
src/part-progress/part-progress.controller.ts
src/part-progress/part-progress.module.ts
src/part-progress/part-progress.repository.ts
src/part-progress/part-progress.service.spec.ts
src/part-progress/part-progress.service.ts
src/part-progress/part-progress.swagger.ts
src/progress/progress.swagger.ts
src/quizzes/dto/create-quiz.dto.ts
src/quizzes/entities/quizzes.entity.ts

#44 
part 와 user 사이에 새로운 상태가 필요했습니다.
유저의 파트 진행도를 볼 수 있는 part-progress API를 작성했습니다.
1. `GET /users/:id/parts-progress` 요청입니다.
```ts
[
{
"userId": 1,
"partId": 3,
"status": "LOCKED"
}
]
```
위처럼 특정유저의  파트 진행 상태를 모두 보여줍니다. 
2. `PUT /users/:id/parts-progress/parts/:partId`
```ts
{
"status": "LOCKED"
}
```
생성 및 수정에 관한 요청입니다.
status 값을 넣어줘야 합니다.
3. PartStatus 값들
```ts
enum PartStatus {
LOCKED
STARTED
IN_PROGRESS
COMPLETED
}
```
위처럼 enum 값 4개를 정했습니다.
4. prisma schema 가 수정되며 마이그레이션 파일이 추가 됩니다.
백엔드 분들은 필히 prisma 마이그레트  해주세요.
-

part progress API 작성

---

src/part-progress/dto/create-part-progress.dto.ts
src/sections/dto/res-section.dto.ts
src/sections/sections.controller.ts
src/sections/sections.repository.ts
src/sections/sections.service.ts
src/sections/sections.swagger.ts

#49 
1. section 모듈에 새로운 api
`GET /section/{id}/users/{id}/part-status`를 작성했습니다.
기존의 `sections/{id}` 요청이 단일 section정보와 관련된 part정보를 가져왔는데
추가로 part에 partProgress의 status를 추가하는 api 입니다.
```ts
// res 예시
{
"id": 1,
"name": "변수",
"part": [
{
"id": 1,
"sectionId": 1,
"name": "변수명",
"status": "LOCKED"
},
{
"id": 2,
"sectionId": 1,
"name": "const",
"status": "LOCKED"
},
{
"id": 3,
"sectionId": 1,
"name": "let"
}
]
}
```
이제 다음 작업으로 생각해봐야하는건, 위 예시중
```ts
{
"id": 3,
"sectionId": 1,
"name": "let"
}
```
처럼 status 가 안나오는 경우를 없애는 것입니다.
해당 상황은 user 1번이 part 3번에 대한 진행도 정보 레코드가 아예 없는 상황입니다. 그래서
**1. 유저가 생성될때, 기본적으로 모든 part에 대한 partProgress 를 생성해야합니다.**
그 다음 
**2. 새로운 part가 생성될때 모든 user에 대해서 새로 추가된 part에 대한 진행도(partProgress)를 만들어야합니다.**
이 두가지 작업이 다음 pr에서 만들어질 예정입니다.

section/{id}/users/{id}/part-status  API 작성

---

src/parts/parts.repository.ts
src/parts/parts.service.ts

#58 
위 이미지처럼 설계 되었어야할 order 가 아래 이미지처럼 생성되고 업데이트 되던 에러를 수정했습니다.

파트의 순서(order) 값이 중첩되지 않았던 오류 수정

---

.github/workflows/main.yml
prisma/migrations/20250103050017_create_user_hp_and_change_user_schema/migration.sql
prisma/migrations/20250103051335_relation_user_hp/migration.sql
prisma/migrations/20250103052032_change_user_hp_table_name/migration.sql
prisma/schema.prisma
src/app.module.ts
src/sections/sections.service.ts
src/users/constants/user-experience.constant.ts
src/users/controllers/user-hp.controller.spec.ts
src/users/controllers/user-hp.controller.ts
src/users/dtos/create-user.dto.ts
src/users/dtos/res-user-hp.dto.ts
src/users/dtos/response-user.dto.ts
src/users/dtos/update-hp.dto.ts
src/users/entities/user-hp.entity.ts
src/users/modules/user-hp.module.ts
src/users/modules/users-core.module.ts
src/users/modules/users.module.ts
src/users/repositories/user-hp.repository.ts
src/users/services/user-hp.service.spec.ts
src/users/services/user-hp.service.ts
src/users/services/users.service.ts
src/users/swaggers/user-hp.swagger.ts

#61 
cokoedu의 유저 생명력 관련 api 입니다. 이번 api 부터 유저id를 url 로 받지 않고 토큰에서 유저 id를 받도록 바꿨습니다.
**1. GET users/user-hp**
유저 생명력을 조회합니다.
유저id, 유저hp, 유저hp storage(최대생명력)을 보여줍니다.
이 get 요청은 유저 생명력 리차지의 이벤트 트리거로 사용됩니다.
**2. PATCH users/user-hp**
유저hp, 유저hp storage 두 가지를 옵셔널로 받아 수정합니다.
두 값은 최소 0 , hp는 최대 hpStorage 값을 줄 수 있습니다. 자세한 내용은 스웨거 참조
**3. 유저 생명력 최대로 채우기**
유저 생명력 업데이트 후 20분 이 지나면 
get 요청시 유저 hp 를 hpStorage값으로 올립니다. (리차지)
**4. user 관련 모듈들의 요청 흐름을 위해 모듈들을 정리했습니다.**
app모듈 -> user core모듈 -> users모듈
-> user-hp모듈
-> user-경험치 모듈
-> user-포인트 모듈
-> 방향은 의존성입니다.
**5. user-hp 모델생성 및 user모델 수정**
마이그레이트 디렉토리 3개가 추가 되었습니다. 
develop에 pr합쳐진 후 pull 하시기 전에 user테이블 비우고 하셔야합니다. (데이터 날라감)
user-hp 테이블은 user 삭제시 Cascade 옵션입니다.
**6. 마지막으로 user-hp 테이블의 레코드는 
유저 생성시 자동으로 생성됩니다. (트랜젝션 완료)**

유저 생명력 api

---

src/main.ts
src/users/controllers/user-hp.controller.ts
src/users/dtos/res-user-hp.dto.ts
src/users/dtos/update-hp.dto.ts
src/users/swaggers/user-hp.swagger.ts

#63 
```ts
export const ApiUserHp = {
getUserHp: () => {
return applyDecorators(
ApiCookieAuth('accessToken'),    <-이거 적용했음
ApiOperation({
summary: '인증된 유저의 hp정보 조회',
description: `
1. 유저 id, 유저 hp, 유저 hpStorage(최대 hp통)를 보여줌
2. GET 요청은 유저hp 리차지의 트리거로 사용됨
3. 유저 생명력 업데이트 후 ${HP_FULL_RECHARGE_TIME / 60 / 1000}분 이 지나면
GET 요청으로 생명력 조회시 생명력이 hpStorage 수치까지 가득참
`,
}),
```
-

access토큰값을 넣는 스웨거 authorize 버튼(쿠키)

---

src/sections/sections.service.ts

#74 
404를 띄워야 하는데 로직상 문제가 있어서 500이 뜨던 문제를 해결합니다.

GET /section/id 에서 찾을 수 없는 404상태에 500으로 띄우던 에러 수정

---

.github/workflows/main.yml
src/common/pipes/positive-int/positive-int.pipe.ts
src/sections/sections.controller.ts

#80 
section/parts 요청이 section/:id 엔드포인트로 받아지는 버그가 생겼습니다
컨트롤러에서 엔드포인트 순서를 변경해 해결하는 pr 입니다.

section 엔드포인트 순서변경

---

prisma/migrations/20250122075156_daily_quest_create/migration.sql
prisma/migrations/20250122085602_add_created_at_updated_at/migration.sql
prisma/schema.prisma
src/app.module.ts
src/daily-quests/daily-quest.swagger.ts
src/daily-quests/daily-quests.controller.spec.ts
src/daily-quests/daily-quests.controller.ts
src/daily-quests/daily-quests.interpace.ts
src/daily-quests/daily-quests.module.ts
src/daily-quests/daily-quests.repository.ts
src/daily-quests/daily-quests.service.spec.ts
src/daily-quests/daily-quests.service.ts
src/daily-quests/dto/create-daily-quest.dto.ts
src/daily-quests/dto/res-daily-quest.dto.ts
src/daily-quests/dto/update-daily-quest.dto.ts
src/daily-quests/entities/daily-quest.entity.ts

#73 
일일퀘스트 내용을 조회 및 생성,수정,삭제 하는 api 입니다.
실제 유저가 일일퀘스트를 받고 데이터를 저장하는 api는 다음 이슈에서 작성할 예정입니다.

일일퀘스트 기본 crud 작성

---

src/admin/admin.controller.ts
src/admin/admin.swagger.ts
src/app.controller.ts
src/auth/auth-swagger.ts
src/auth/auth.controller.ts
src/ranking/dtos/ranking-pagination-res.dto.ts
src/ranking/dtos/ranking-query.dto.ts
src/ranking/dtos/ranking-sort.dto.ts
src/ranking/dtos/user-ranking.dto.ts
src/ranking/entities/ranking.entity.ts
src/ranking/ranking.swagger.ts
src/ranking/rankings.controller.ts
src/ranking/rankings.module.ts
src/ranking/rankings.repository.ts
src/ranking/user-rankings.controller.ts
src/users/dtos/response-user.dto.ts

#87 
swagger 에 auth 와 관련된 api 스웨거를 생성했습니다
- `/` 엔드포인트 Swagger 문서에서 삭제
-  `auth/google` 이나 `auth/google/callback` 같은 요청은 직접적인 요청이 아니라 문서에서 제외했습니다.
- Swagger 문서 'auth' 부분 생성

Auth Swagger 생성

---

.github/workflows/main.yml
src/part-progress/part-progress.controller.ts
src/part-progress/part-progress.repository.ts
src/part-progress/part-progress.service.ts
src/part-progress/part-progress.swagger.ts
src/parts/parts.repository.ts
src/parts/parts.service.ts
src/parts/parts.swagger.ts

#94 
**api 호출 전**
**api 호출 후**
위처럼 유저 파트의 status를 complet로 만들고
추가로 다음 파트를 started로 변경하는 api 입니다.

parts/status를 complet 로 만드는 api

---

src/part-progress/part-progress.module.ts
src/part-progress/part-progress.repository.ts
src/part-progress/part-progress.service.ts
src/parts/parts.controller.ts
src/parts/parts.service.ts

#97 
서비스 로직을 추가해 마지막 파트가 completed이면 started로 파트상태가 추가되도록 변경했습니다.
참조 https://github.com/modern-agile-team/8term-coko-back/pull/100#discussion_r1940753929

locked상태의 파트를 완료하지 못하게 변경 + 파트 추가시 디폴트 상태 조건을 추가

---

src/items/items.controller.ts
src/items/items.swagger.ts

#109 #105 
아이템 스웨거 문서에 문제가 생겨
서버에러가 발생했습니다.
일단 관련 코드 주석처리로 저장합니다.

아이템 스웨거 잠시 주석처리

---

.github/workflows/main.yml
package-lock.json
src/app.module.ts
src/main.ts
src/users/controllers/user-items.controller.ts
src/users/swagger-dacorator/get-user-items.decorators.ts

#105 #109 
이전에 만들었던 임시 items api를 넣었었는데, app.module.ts에 넣지 않았어서 스웨거에서 확인이 안되었습니다. 
app.module.ts에 items module를 추가했습니다.

docs/#105/items 앱모듈 파일에 추가, 토큰 반복변경 방지 코드 (시험)

---

package-lock.json
package.json
prisma/migrations/20250212021729_update_daily_quest/migration.sql
prisma/schema.prisma
src/app.module.ts
src/daily-quests/daily-quests.interface.ts
src/daily-quests/dto/create-daily-quest.dto.ts
src/daily-quests/dto/res-daily-quest.dto.ts
src/daily-quests/entities/daily-quest.entity.ts
src/daily-quests/users-daily-quests/dto/res-user-daily-quest.dto.ts
src/daily-quests/users-daily-quests/dto/update-users-daily-quest.dto.ts
src/daily-quests/users-daily-quests/users-daily-quests.controller.ts
src/daily-quests/users-daily-quests/users-daily-quests.module.ts
src/daily-quests/users-daily-quests/users-daily-quests.service.ts
src/progress/progress.repository.ts
src/progress/progress.service.ts

#120 
**1. api 한개 삭제 되었습니다. 이제 클라이언트에서 일일퀘스트 수정을 요청하지 않고 서버에서 관리합니다.
2. progress create 또는 update 시 유저 일일 퀘스트를 update 합니다.
3. nestjs event-emitter를 사용해 이벤트 발생과, 이벤트시 실행을 구현했습니다.**
event-emitter를 사용한 이유는 progress 모듈에 usersDailyQuest 모듈을 의존성주입하기 싫어서 입니다.
지금까지 왜 잘 했는데 갑자기 그러냐?! 라고 물어보시면; 대단한 이유는 없습니다 😅
usersDailyQuest를 업데이트하는 순간이 기존 "patch 요청을 클라이언트가 보낼때" 라는 이벤트에서
"progress 업데이트시" 라는 이벤트로 변경되면서
새로운 우리의 비즈니스 로직 변경이 progress 모듈의 수정으로 이어지는게 생각보다 싫었습니다...
기존 이벤트 기반 에러처리를 https://github.com/honey-moa/honey-moa-server 허니모아에서 보면서
저희 메서드 실행도 이렇게 해보면 간단하지 않을까 하면서 작성했습니다.
참조 : https://docs.nestjs.com/techniques/events
생각보다 깊게 참조하지 않아서 지적할 사항이 많을거 같습니다. 😅
- 더 좋은 이벤트 처리에 대해서 공부 더 해보고 리팩 이어나가겠습니다.

user daily quest update api 삭제 및 서버 이벤트 확인으로 변경

---

src/daily-quests/users-daily-quests/dto/update-users-daily-quest.dto.ts
src/daily-quests/users-daily-quests/users-daily-quests.service.ts

#127 
erd 내용처럼 
유저의 일일퀘스트 진행도 `(conditionProgress)`가 있습니다.
이 값은 `progress`에서 오늘자 문제를 맞춘 데이터를 조회해 카운트 값을 가져와 저장됩니다.
오늘 12문제를 맞추면 목표`(condition)`가 10 이여도
`목표 : 12/10`
처럼 진행도가 목표를 상회하는 에러가 있었습니다.
해당서비스 로직을 변경해 이 에러를 수정합니다.

유저의 일일퀘스트 진행도가 일일퀘스트 목표치를 상회 하던 에러 수정

---

src/challenges/challenges.interface.ts
src/challenges/challenges.module.ts
src/challenges/challenges.repository.ts
src/challenges/const/challenges.constant.ts
src/challenges/dto/create-challenges.dto.ts
src/challenges/dto/res-challenges.dto.ts
src/challenges/events/challenges.event.ts
src/challenges/level-clear-challenges.service.ts
src/challenges/section-clear-challenges.service.ts
src/challenges/user-challenges/user-challenges.interface.ts
src/challenges/user-challenges/user-challenges.repository.ts
src/part-progress/part-progress.service.ts
src/users/controllers/user-experience.controller.ts
src/users/services/user-experience.service.ts

#149 
도전과제 레벨 10 달성, 20달성 등
레벨 클리어에 관한 도전과제 달성을 체크하는 세부로직 입니다.
1. challenge 모듈에서  challenge.event -> level-clear-challenge.service -> 각 모듈의 repository 로
이어지는 흐름의 이벤트 로직을 작성했습니다. 이벤트 트리거는 progress 모듈의 progress서비스의 upsert메서드 실행입니다.
2.  level-clear-challenge.service 세부 로직입니다.
1) 유저 정보와 클래스 내부 타입으로 유저 도전과제를 조회후 업데이트 해줍니다.

레벨클리어 도전과제 세부로직 작성

---

src/challenges/challenges.repository.ts
src/challenges/challenges.service.ts
src/challenges/dto/query-challenges.dto.ts
src/challenges/dto/res-challenges.dto.ts
src/challenges/level-clear-challenges.service.ts
src/challenges/user-challenges/user-challenges.repository.ts
src/challenges/user-challenges/user-challenges.service.ts

#159 
기존 페이지네이션을 위해 받던 page, limit 값 말고도 정렬을위한 challengeType 값을 url쿼리스트링으로 받습니다.
이제 challengeType 별로 정렬이 가능합니다.
추가사항으로
POST /challenges 요청시 유니크값인 challengeType과 condition값의 조합을 
확인하지 않는걸 보고 
조합값 유니크를 확인하는 코드를 추가했습니다.
```ts
async chackedTypeAndConditionUnique(typeAndCondition: {
challengeType: ChallengeType;
condition: number;
}): Promise<Challenge> {
const challenges =
await this.challengesRepository.findOneByChallengeTypeAndCondition(
typeAndCondition,
);
if (challenges) {
throw new ConflictException(
`도전과제 타입과 컨디션의 조합은 유니크 해야합니다.`,
);
}
return challenges;
}
```

GET /users/me/challenges api 페이지네이션 요청에 정렬 추가

---

src/challenges/user-challenges/user-challenges.repository.ts

#170 
유저 도전과제를 배열로 보열줄때, 기존 true를 먼저 보여주는것에 추가해
1. 타입별로 정렬 , 내림차순
2. conditon으로 다시정렬, 올림차순
두 옵션을 넣어서 더 명확한 순서로 보여줍니다.
이제 클라이언트는 
1. 도전과제 완료를 먼저봄
2. 도전과제 실패 중 타입별로 묶어서 보여짐
3. 도전과제 타입들 중에는 conditons 올림차순으로 보임 ( 7일연속 -> 14일연속-> 21연속 또는 1섹션 -> 2섹션 -> 3섹션 이런식)
위와같은 순서로 정보를 받습니다.

유저도전과제 orderby 옵션을 더 명확하게 정의

---

src/challenges/challenges.module.ts
src/challenges/challenges.repository.ts
src/challenges/challenges.service.ts
src/challenges/const/challenges.constant.ts
src/challenges/dto/query-challenges.dto.ts
src/challenges/events/challenges.event.ts
src/challenges/first-wrong-answer.challenges.service.ts
src/challenges/user-challenges/user-challenges.repository.ts
src/challenges/user-challenges/user-challenges.service.ts
src/daily-quests/users-daily-quests/users-daily-quests.service.ts
src/progress/progress.service.ts

#156 
도전과제 중
"처음으로 문제를 틀림" 도전과제를 서버에서 확인하는 작업입니다.
이전 작업들과 비슷한 작업입니다.
추가적으로 
요즘 작성중에 드는 생각은, 세부 유저 도전과제 서비스들의 로직이 안그래도 비슷한데,
특히 "처음 아이템구매", "처음 문제를 트림" 도전과제 등 앞으로 **이벤트**라고 명시할 도전과제들은
완전 똑같은 코드가 중복되고 있어서 이 중복을 어떤식으로 없앨지 고민이 됩니다.

"처음으로 문제를 틀림" 도전과제 세부로직

---

src/items/dto/response-item.dto.ts
src/items/items.service.ts
src/users/controllers/user-items.controller.ts
src/users/dtos/response-user-equipped.dto.ts
src/users/dtos/response-userItems-pagination.dto.ts
src/users/swagger-decorator/get-equipped-user-items.decorators.ts
src/users/swagger-decorator/get-user-items.decorators.ts

`GET users/me/itmes/equipped` 요청은 유저의 아이템 장착여부를 알려줍니다.
기존에는 **유저아이템+아이템** 객체배열을 전달해서 이 형태를 알려줬습니다.
**기존**
```ts
[
{
"id": 31,
"userId": 5,
"itemId": 39,
"purchasedAt": "2025-02-26T07:40:01.011Z",
"isEquipped": true,
"item": {
"id": 39,
"name": "파랑 물약",
"price": 0,
"image": "",
"mainCategoryId": 4,
"subCategoryId": 8
}
}
]
```
이번 이슈를 통해 **아이템** 객체 배열에 **isEquipped** 여부만 붙여서 클라이언트에 주는 데이터를 가공해서 줍니다.
**변경**
```ts
[   
{    
"id": 1,
"name": "겨울옷",
"price": 5000,     
"image": "Group 370.svg",     
"isEquipped": true  
} 
]
```
`GET users/me/itmes` 요청은 특정 유저의 아이템과 장착여부를 페이지네이션 형태로 알려줍니다.
`GET users/me/itmes/equipped` respose 데이터 구조변경처럼 해당 api 도 변경했습니다.
**변경**
```ts
{
"totalCount": 2,
"totalPage": 1,
"currentPage": 1,
"contents": [
{
"id": 5,
"name": "요정-신발",
"price": 6000,
"image": …
```

유저 아이템 장착여부 조회 api의 res정보데이터 변경

---

src/users/dtos/response-user-equipped.dto.ts

#181 
참조 이슈의 클라이언트에게 주는 데이터에서 subCategoryId 값을 추가로 담아서 줍니다.

#181의 유저아이템 response DTO에 서브카테고리 아이디 값 추가

---

src/admin/admin.swagger.ts
src/ranking/ranking.constant.ts
src/users/constants/user-hp.constant.ts
src/users/controllers/user-experience.controller.ts
src/users/controllers/user-point.controller.ts
src/users/controllers/users.controller.ts
src/users/dtos/update-experience.dto.ts
src/users/swagger-decorator/delete-user-decorators.ts
src/users/swagger-decorator/get-all-users-decorators.ts
src/users/swagger-decorator/get-equipped-user-items.decorators.ts
src/users/swagger-decorator/get-me-decorators.ts
src/users/swagger-decorator/get-user-decorators.ts
src/users/swagger-decorator/get-user-experience-decorators.ts
src/users/swagger-decorator/get-user-point-decorators.ts
src/users/swagger-decorator/patch-user-decorators.ts
src/users/swagger-decorator/patch-user-experience-decorators.ts

#188
이벤트 상수 시간 변경 
- 생명력 리필 시간 3분으로 변경
- 총 정답수 컬럼 업데이트 시간 2분으로 변경

이벤트 상수 시간 변경 

---

src/ranking/rankings.service.ts

#194
랭킹 페이지네이션 로직을 수정했습니다
마지막 페이지에 보여줄 사용자가 2명일때 반복문이 limit 값인 5만큼 돌아가기 때문에
참조에러가 떴었습니다. 
-> 이제 페이지에 있는 사용자 만큼 반복문이 돌아갑니다

fix/#194/랭킹 페이지내이션 로직 수정
