prisma/migrations/20241208080451_cascade_token/migration.sql, prisma/schema.prisma, src/users/controllers/users.controller.ts, src/users/services/users.service.ts
#42 
user controller에서  await 이 사용안된걸 확인해서 수정했습니다.
추가로 token 모델에서 user와의 릴레이션 쉽 부분에 user가 삭제될시의 옵션이 설정되있지를 않아서
casecade 옵션을 추가했습니다. 릴레이션 쉽 설정시 자주 일어나는 부분이라 다들 주의가 필요해 보입니다.
=> user 삭제시 서버가 꺼지던 에러 수정

.github/workflows/main.yml
=> bugfix/#68/액션 워크플로우 변경

src/sections/sections.controller.ts, src/sections/sections.service.ts, src/sections/sections.swagger.ts
#74 
삭제한 api를 다시 생성합니다
추가로 status 값을 가져오도록 로직을 수정합니다.
=> sections/{id} API 복구 및 수정

.github/workflows/main.yml, src/auth/auth.controller.ts
#77
- 로그아웃 api 의 오타를 수정했습니다
- `accessTokens` 이름의 가드 이름을 `accessToken` 으로 수정
=> fix/#77/로그아웃 api 오타 수정

src/part-progress/part-progress.controller.ts, src/parts/parts.controller.ts, src/progress/dto/res-progress.dto.ts, src/progress/progress.controller.ts, src/progress/progress.swagger.ts, src/quizzes/quizzes.controller.ts, src/quizzes/quizzes.module.ts, src/quizzes/users-quizzes.controller.ts, src/sections/sections.controller.ts, src/sections/users-sections.controller.ts
#84 
위처럼 제가 작업한 엔드포인트에서 
userId가 필요한 엔드포인트들의 url을  users/me라고 통합시켰습니다.
-
=> url - users/:id -> users/me

src/part-progress/part-progress.controller.ts
#89 
이슈 참고해주시면 감사하겠습니다.
123 중 1만 구현했습니다. 너무많은 리소스를 잡아먹는거 같아서
모두 그대로 놓고 url과 스웨거 태그만 변경했습니다.
=> modify/#84/엔드포인트url 수정 및 스웨거태그 변경

src/auth/services/token.service.ts
=> feat/#91/admin 토큰 만료 시간 연장

src/part-progress/part-progress.controller.ts
=> modify/#94/api 다시 소생

.github/workflows/main.yml, src/ranking/dtos/res-my-ranking.dto.ts, src/ranking/rankings.service.ts
#98 
응답 값 이름을 `myranking` 에서 -> `ranking` 으로 변경
=> 랭킹 응답 데이터 수정

.github/workflows/main.yml
=> docs/#105/워크플로우 변경

.github/workflows/main.yml, package-lock.json
#114
#103 이슈에서 유저 일일퀘스트 API가 추가되며
nestjs 스케쥴러의 디팬던시가 추가 되었습니다. @dg1418 
`git pull` 로 github 리포지토리와 동기화 할때 충돌부분이 잘 해결되지 않아 생겨난 에러로 추정됩니다.
=> package-lock.json 중복 에러 제거

src/ranking/dtos/ranking-sort.dto.ts, src/ranking/entities/ranking.entity.ts, src/ranking/utils/filter-utils.ts, src/ranking/utils/sort-utils.ts
#166
랭킹 요청 쿼리값 변수이름 변경
#116 참고해주시면 됩니다
=> 랭킹 요청 쿼리값 변수이름 변경

src/items/dto/create-item.dto.ts, src/items/dto/items-pagination-query.dto.ts, src/items/dto/items-pagination-response.dto.ts, src/items/dto/update-item.dto.ts, src/items/items.controller.ts, src/items/items.module.ts, src/items/items.repository.ts, src/items/items.service.ts, src/ranking/dtos/ranking-pagination-res.dto.ts
#105, #129 
create
update
get 전체조회 페이지네이션
refactoring 있었습니다
🤔`기존` : **모든 아이템 조회(페이지네이션 적용)** , **아이템 카테고리별로 조회 (페이지네이션 적용 x)**
💡-> `수정 작업` : **아이템 카테고리별로 조회 (페이지네이션 적용해서)** : `2가지 조회 기능을 하나로 합쳤습니다.`
2번째 작업에 대해 refactoring 을 먼저 했습니다. 이후에 계속 refactoring 을 진행할 것이라서 하나씩 issue생성하며 pr 올리겠습니다. 
- 현재 이 pr에 comment가 많고 이에 따른 수정할 것들이 많습니다. 하나씩 issue생성하며 수정해나가겠습니다.
`2번째 작업` 리뷰 중심적으로 부탁드립니다. 😊
=> refactor/#105/iItems api - 아이템 카테고리별로 조회, 페이지네이션 적용

src/admin/admin.controller.ts, src/admin/admin.module.ts, src/admin/admin.service.ts, src/app.module.ts, src/auth/jwt/jwt.startegy.ts, src/auth/services/cookie.service.ts, src/auth/services/token.service.ts
#133
- admin 토큰의 이름을 변경
- admin 토큰의 이름을 변경
=> admin 토큰 이름 변경

src/items/dto/items-pagination-query.dto.ts, src/items/dto/update-item.dto.ts, src/items/items.controller.ts, src/items/items.service.ts
#132 
PATCH 기능에서 아이템의 정보를 수정할 때, 하나의 필드만 수정하고 싶어도 모든 필드를 변경해야만 수정이 적용되는 문제가 있었습니다. 
DTO 정의와 서비스 코드에서 모든 필드를 필수로 요구하는 구조로 인해 발생했습니다.
=> fix/#132/PATCH 오류 해결

src/daily-quests/users-daily-quests/dto/update-users-daily-quest.dto.ts, src/items/dto/create-item.dto.ts, src/items/items.controller.ts
#132 
PATCH 기능, mainCategoryId, subCategoryId에서 dto type지정을 하지 않아, 유효성검사 문제가 생겼었습니다.
제대로 테스트 후에 pr 올리겠습니다 ㅎ..🥲😅
=> fix/#132/PATCH 오류 해결2

src/items/dto/create-item.dto.ts, src/items/dto/items-pagination-query.dto.ts, src/items/dto/response-item.dto.ts, src/items/dto/update-item.dto.ts, src/items/items.controller.ts, src/items/items.service.ts, src/items/items.swagger.ts
#132 #142 
1. items api 에서 patch의 mainCategoryId, subCategoryId 수정요청이 제대로 작동하지 않아, dto 를 새롭게 작성했습니다.
2. items api 변경에 따른 기존의 swagger를 재작업했습니다.
=> items api PATCH 오류해결 및 Swagger 재작업

src/challenges/level-clear-challenges.service.ts
=> 메서드 파라미터 순서변경

src/challenges/section-clear-challenges.service.ts, src/part-progress/part-progress.repository.ts
#164 
이슈 내용처럼 섹션아이디를 추가하여 조회합니다.
=> bugfix/#164/sectionId를 조회할때 추가

src/challenges/user-challenges/user-challenges.repository.ts
=> 타입별 정렬 내림차순을 올림차순으로 변경

src/attendance/attendance.service.ts, src/challenges/const/challenges.constant.ts, src/challenges/events/challenges.event.ts, src/common/constants/event-constants.ts, src/daily-quests/users-daily-quests/users-daily-quests.service.ts, src/part-progress/part-progress.service.ts, src/progress/progress.service.ts, src/ranking/rankings.service.ts, src/users/services/user-experience.service.ts, src/users/services/user-hp.service.ts, src/users/services/user-items.service.ts
#184
사진과 같이 이벤트 상수 모아줬습니다.
- 이벤트 상수 위치 변경
=> 이벤트 상수 모으는 작업

src/challenges/events/challenges.event.ts, src/ranking/rankings.event.ts, src/users/controllers/user-experience.controller.ts, src/users/controllers/user-point.controller.ts, src/users/controllers/users.controller.ts, src/users/events/user-hp.event.ts
#190
- 관련 이슈에 있는 내용을 작업했습니다.
주간 랭킹 집계 이벤트명 수정 ( 포인트 -> 정답수)
- 추가로 반환타입 없는 컨트롤러에 반환타입 지정했습니다.
=> 주간 랭킹 집계 이벤트명 수정

src/ranking/utils/filter-utils.ts
#192
레벨 랭킹 정렬 조건중 3차 조건을 **포인트에서 -> 총 정답수로 변경**했습니다
=> 레벨 랭킹 정렬 조건 수정

package-lock.json, package.json, src/app.module.ts, src/app.service.ts, src/auth/services/auth.service.ts, src/challenges/events/challenges.event.ts, src/common/constants/event-constants.ts, src/logger/logger.config.ts, src/logger/logger.constants.ts, src/logger/logger.filters.ts, src/logger/logger.module.ts, src/main.ts, src/sse/sse.service.ts
#200
- Winston 라이브러리로 Logger 구현
- Winston 라이브러리 설치
- error 로그와 error가 아닌 로그 파일 분리해서 저장
- 한 파일의 크기는 20mb, 파일 생명주기?는 2주로 설정했습니다.
로그를 찍고 싶은 서비스에서 아래와 의존성 같이 주입한 후 
```
@Inject(WINSTON_MODULE_NEST_PROVIDER)
private readonly logger: LoggerService,
```
```
this.logger.log('기본 로깅');
this.logger.debug('debug 로깅');
```
아래와 같은 에러 로깅이 가능합니다 
보통 예상치 못한, 서비스로직의 예외처리가 아닌 500번대 서버 에러를 로깅합니다.
```
this.logger.error('error 로깅');
```
에러 레벨 이상(error, fatal) error 로그 파일에
외에는 일반 로그 파일에 저장됩니다.
[로그 레벨이란?](https://sharonprogress.tistory.com/198) 블로그 참고해주세여
=> feat/#200/로거 생성

src/challenges/ranking-challenges.service.ts, src/challenges/user-challenges/user-challenges.repository.ts, src/ranking/rankings.controller.ts
#202
- 기존 completed 된 도전과제도 가장 최신 랭킹 달성시간으로 업데이트시킵니다.
=> 매주 랭킹 1, 2, 3 등의 데이터 업데이트
